[env]
_.python.venv = { path = ".venv", create = true }

[settings]
idiomatic_version_file_enable_tools = ["python"]

[tasks.install]
alias = "i"
run = "uv sync --all-extras"

[tasks.lint]
run = "ruff check ."

[tasks.test]
run = "pytest --cov=app --cov-report=term-missing"
