{{- if and (eq (.Values.config.agentsEnabled | toString) "true") .Values.persistence.agentEmbeddingModels.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "securo.fullname" . }}-agent-embedding-models
  labels:
    {{- include "securo.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.agentEmbeddingModels.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.agentEmbeddingModels.size | quote }}
  {{- if .Values.persistence.agentEmbeddingModels.storageClass }}
  {{- if (eq "-" .Values.persistence.agentEmbeddingModels.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.persistence.agentEmbeddingModels.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
