{{- if not .Values.global.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "securo.fullname" . }}-secrets
  labels:
    {{- include "securo.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secret }}
  {{- if $value }}
  {{ $key | snakecase | upper }}: {{ tpl (print $value) $ | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
